use std::sync::Arc;

use crate::session_runtime::SessionHandle;

pub fn slash_command_metadata(name: &str, args: &str) -> String {
    let mut body =
        format!("<command-message>{name}</command-message>\n<command-name>/{name}</command-name>");
    let trimmed_args = args.trim();
    if !trimmed_args.is_empty() {
        body.push_str(&format!("\n<command-args>{trimmed_args}</command-args>"));
    }
    body
}

pub fn slash_metadata_message(metadata: &str) -> coco_messages::Message {
    let attachment = coco_messages::AttachmentMessage::api(
        coco_types::AttachmentKind::SlashCommandMetadata,
        coco_messages::LlmMessage::user_text(metadata),
    );
    coco_messages::Message::Attachment(attachment)
}

pub fn slash_text_messages(
    command: &str,
    args: &str,
    text: &str,
    is_sensitive: bool,
) -> Vec<coco_messages::Message> {
    coco_messages::build_slash_command_messages(command, args, text, is_sensitive)
}

pub fn slash_result_messages(
    command: &str,
    args: &str,
    text: &str,
    is_error: bool,
) -> Vec<coco_messages::Message> {
    if is_error {
        coco_messages::build_slash_command_error_messages(command, args, text)
    } else {
        slash_text_messages(command, args, text, /*is_sensitive*/ false)
    }
}

pub async fn append_slash_result_to_history_and_emit(
    session: &SessionHandle,
    event_tx: tokio::sync::mpsc::Sender<coco_types::CoreEvent>,
    command: &str,
    args: &str,
    text: &str,
    is_error: bool,
) -> Vec<Arc<coco_messages::Message>> {
    session
        .append_messages_to_history_and_emit(
            slash_result_messages(command, args, text, is_error),
            Some(event_tx),
        )
        .await
}

pub fn context_usage_messages(
    args: &str,
    result: coco_types::ContextUsageResult,
) -> Vec<coco_messages::Message> {
    coco_messages::build_context_usage_messages(args, result)
}

pub async fn append_context_usage_to_history_and_emit(
    session: &SessionHandle,
    event_tx: tokio::sync::mpsc::Sender<coco_types::CoreEvent>,
    args: &str,
    result: coco_types::ContextUsageResult,
) -> Vec<Arc<coco_messages::Message>> {
    session
        .append_messages_to_history_and_emit(context_usage_messages(args, result), Some(event_tx))
        .await
}

pub async fn append_meta_text_to_history(
    session: &SessionHandle,
    text: &str,
) -> Vec<Arc<coco_messages::Message>> {
    session
        .append_messages_to_history(vec![coco_messages::create_meta_message(text)])
        .await
}

pub fn system_push_message(kind: coco_tui::SystemPushKind) -> coco_messages::Message {
    let system = match kind {
        coco_tui::SystemPushKind::Informational {
            level,
            title,
            message,
        } => {
            coco_messages::SystemMessage::Informational(coco_messages::SystemInformationalMessage {
                uuid: uuid::Uuid::new_v4(),
                level,
                title,
                message,
            })
        }
        coco_tui::SystemPushKind::LocalCommand { command, output } => {
            coco_messages::SystemMessage::LocalCommand(coco_messages::SystemLocalCommandMessage {
                uuid: uuid::Uuid::new_v4(),
                command,
                output,
            })
        }
        coco_tui::SystemPushKind::PermissionRetry { tool_name, message } => {
            coco_messages::SystemMessage::PermissionRetry(
                coco_messages::SystemPermissionRetryMessage {
                    uuid: uuid::Uuid::new_v4(),
                    tool_name,
                    message,
                },
            )
        }
    };
    coco_messages::Message::System(system)
}

pub async fn append_system_push_to_history_and_emit(
    session: &SessionHandle,
    event_tx: tokio::sync::mpsc::Sender<coco_types::CoreEvent>,
    kind: coco_tui::SystemPushKind,
) -> Vec<Arc<coco_messages::Message>> {
    session
        .append_messages_to_history_and_emit(vec![system_push_message(kind)], Some(event_tx))
        .await
}

pub fn local_command_messages(
    command: &str,
    output: &str,
    should_respond: bool,
) -> Vec<coco_messages::Message> {
    let mut messages = Vec::new();
    if !should_respond {
        messages.push(coco_messages::create_meta_message(
            "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>",
        ));
    }
    messages.push(coco_messages::Message::System(
        coco_messages::SystemMessage::LocalCommand(coco_messages::SystemLocalCommandMessage {
            uuid: uuid::Uuid::new_v4(),
            command: command.to_string(),
            output: output.to_string(),
        }),
    ));
    messages
}

pub async fn append_local_command_to_history_and_emit(
    session: &SessionHandle,
    event_tx: tokio::sync::mpsc::Sender<coco_types::CoreEvent>,
    command: &str,
    output: &str,
    should_respond: bool,
) -> Vec<Arc<coco_messages::Message>> {
    session
        .append_messages_to_history_and_emit(
            local_command_messages(command, output, should_respond),
            Some(event_tx),
        )
        .await
}

pub fn compact_summary_message(summary: &str) -> Option<coco_messages::Message> {
    if summary.trim().is_empty() {
        return None;
    }
    Some(coco_compact::build_compact_summary_message(summary))
}

pub async fn append_compact_summary_to_history_and_emit(
    session: &SessionHandle,
    event_tx: tokio::sync::mpsc::Sender<coco_types::CoreEvent>,
    summary: &str,
) -> Option<Vec<Arc<coco_messages::Message>>> {
    let message = compact_summary_message(summary)?;
    Some(
        session
            .append_messages_to_history_and_emit(vec![message], Some(event_tx))
            .await,
    )
}

pub fn fork_skill_result_messages(metadata: &str, body: &str) -> Vec<coco_messages::Message> {
    vec![
        slash_metadata_message(metadata),
        coco_messages::create_user_message(body),
    ]
}

pub async fn append_fork_skill_result_to_history_and_emit(
    session: &SessionHandle,
    event_tx: tokio::sync::mpsc::Sender<coco_types::CoreEvent>,
    metadata: &str,
    body: &str,
) -> Vec<Arc<coco_messages::Message>> {
    session
        .append_messages_to_history_and_emit(
            fork_skill_result_messages(metadata, body),
            Some(event_tx),
        )
        .await
}

pub async fn append_slash_text_to_history(
    session: &SessionHandle,
    command: &str,
    args: &str,
    text: &str,
    is_sensitive: bool,
) -> Vec<Arc<coco_messages::Message>> {
    let messages = slash_text_messages(command, args, text, is_sensitive);
    session.append_messages_to_history(messages).await
}

pub fn model_role_change_messages(
    changed: &coco_types::ModelRoleChangedParams,
    display_name: &str,
    is_remote: bool,
) -> Vec<coco_messages::Message> {
    let role_label = title_case_model_role(changed.role);
    let effort_suffix = changed
        .effort
        .map(|effort| format!(" · thinking: {effort}"))
        .unwrap_or_default();
    let display_label = if changed.provider == "moa" {
        format!("{}/{}", changed.provider, changed.model_id)
    } else {
        format!("{}/{}", changed.provider, display_name)
    };
    let output = format!("Set {role_label} → {display_label}{effort_suffix}");
    let mut messages = slash_text_messages(
        "model", /*args*/ "", &output, /*is_sensitive*/ false,
    );
    if let Some(reminder) =
        remote_model_change_reminder_message(changed.role, display_name, is_remote)
    {
        messages.push(reminder);
    }
    messages
}

pub async fn append_model_role_change_to_history_and_emit(
    session: &SessionHandle,
    event_tx: tokio::sync::mpsc::Sender<coco_types::CoreEvent>,
    changed: &coco_types::ModelRoleChangedParams,
    display_name: &str,
    is_remote: bool,
) -> Vec<Arc<coco_messages::Message>> {
    session
        .append_messages_to_history_and_emit(
            model_role_change_messages(changed, display_name, is_remote),
            Some(event_tx),
        )
        .await
}

pub fn remote_model_change_reminder_message(
    role: coco_types::ModelRole,
    display_name: &str,
    is_remote: bool,
) -> Option<coco_messages::Message> {
    if !is_remote || role != coco_types::ModelRole::Main {
        return None;
    }
    Some(coco_messages::wrapping::create_system_reminder_message(
        &format!(
            "The model for this session has been changed to {display_name}. You are now running as {display_name}."
        ),
    ))
}

fn title_case_model_role(role: coco_types::ModelRole) -> String {
    let mut chars = role.as_str().chars();
    chars.next().map_or_else(String::new, |first| {
        format!("{}{}", first.to_uppercase(), chars.as_str())
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn local_command_messages_adds_context_only_caveat_when_not_responding() {
        let messages = local_command_messages("pwd", "/repo", false);

        assert_eq!(messages.len(), 2);
        let caveat = coco_messages::wrapping::extract_text_from_message(&messages[0]);
        assert!(caveat.contains("<local-command-caveat>"));
        match &messages[1] {
            coco_messages::Message::System(coco_messages::SystemMessage::LocalCommand(command)) => {
                assert_eq!(command.command, "pwd");
                assert_eq!(command.output, "/repo");
            }
            other => panic!("expected local command message, got {other:?}"),
        }
    }

    #[test]
    fn local_command_messages_omits_caveat_when_responding() {
        let messages = local_command_messages("pwd", "/repo", true);

        assert_eq!(messages.len(), 1);
        match &messages[0] {
            coco_messages::Message::System(coco_messages::SystemMessage::LocalCommand(command)) => {
                assert_eq!(command.command, "pwd");
                assert_eq!(command.output, "/repo");
            }
            other => panic!("expected local command message, got {other:?}"),
        }
    }

    #[test]
    fn compact_summary_message_marks_non_empty_summary() {
        let message = compact_summary_message("summary text").expect("non-empty summary");

        match message {
            coco_messages::Message::User(user) => {
                assert!(user.is_compact_summary);
                let text = coco_messages::wrapping::extract_text_from_message(
                    &coco_messages::Message::User(user),
                );
                assert!(text.contains("summary text"));
            }
            other => panic!("expected compact user message, got {other:?}"),
        }
    }

    #[test]
    fn compact_summary_message_skips_blank_summary() {
        assert!(compact_summary_message(" \n\t ").is_none());
    }

    #[test]
    fn fork_skill_result_messages_include_metadata_and_body() {
        let messages = fork_skill_result_messages(
            "<command-name>/demo</command-name>",
            "<local-command-stdout>\nok\n</local-command-stdout>",
        );

        assert_eq!(messages.len(), 2);
        match &messages[0] {
            coco_messages::Message::Attachment(attachment) => {
                assert_eq!(
                    attachment.kind,
                    coco_types::AttachmentKind::SlashCommandMetadata
                );
            }
            other => panic!("expected slash metadata attachment, got {other:?}"),
        }
        let body = coco_messages::wrapping::extract_text_from_message(&messages[1]);
        assert!(body.contains("<local-command-stdout>"));
        assert!(body.contains("ok"));
    }

    #[test]
    fn slash_command_metadata_matches_ts_shape() {
        assert_eq!(
            slash_command_metadata("simplify", "focus on tests"),
            "<command-message>simplify</command-message>\n\
             <command-name>/simplify</command-name>\n\
             <command-args>focus on tests</command-args>"
        );
    }

    #[test]
    fn slash_command_metadata_omits_empty_args() {
        assert_eq!(
            slash_command_metadata("simplify", ""),
            "<command-message>simplify</command-message>\n\
             <command-name>/simplify</command-name>"
        );
    }

    #[test]
    fn slash_result_messages_can_build_error_shape() {
        let messages = slash_result_messages("permissions", "bad", "Nope", true);

        assert_eq!(messages.len(), 2);
        let text = coco_messages::wrapping::extract_text_from_message(&messages[1]);
        assert!(text.contains("Nope"));
    }
}
